---
title: "Problem Set 3"
author: "ECON 326 - Industrial Organization - Spring 2020"
date: "Due by 11:59 PM Friday, May 1, 2020 by email"
output: pdf_document
header-includes:
- \usepackage{amsmath}
- \usepackage{multirow, multicol, booktabs}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(mosaic)
```

Please **type** your answers to the following questions in a document and **email it** (as MS Word, PDF, etc) to me. You may still handwrite answers if you will be able to scan and email them if they are easily readable, but this is *not preferred*.

For the few questions that ask you to draw a **graph/diagram**, *try* to do so *on your computer* (use MS Paint, the drawing tools in MS Word or MS Powerpoint, plot points in MS Excel, drawing/notetaking apps, etc.), and save it as an image to include on your homework document. Again, they need not be perfect or to scale, just show that you understand the broad idea. Being able to understand and sketch the graphs is still a very important and useful skill! If all else fails, I will be lenient in grading graph questions if you are unable to technologically include a graph. 

You may work together (and I highly encourage that) but you must turn in your own answers. Your TA, under my supervision, will grade homeworks 70% for completion, and for the remaining 30%, pick one question to grade for accuracy - so it is best that you try every problem, even if you are unsure how to complete it accurately.

# Theory of the Firm

1. If markets are so great, why are there firms? Explain what Coase has to say about the purpose of firms.

\clearpage

2. According to Alchian and Demsetz, what are the problems inherent in *team production* and how does this give rise to firms? How is the "firm" incentivized to solve the team production problem?

\clearpage

3. Explain what asset specificity and quasi-rents are in contracting, and why this helps explain vertical integration and contracts with vertical restraints.

\clearpage

# Antitrust

4. An industry consists of the following firms

| Firm | Market Share (%) |
|------|------------------|
| A | 40 |
| B | 20 |
| C | 10 |
| D | 10 |
| E | 5 |
| F | 5 |
| G | 2 |
| H | 2 |
| I | 2 |
| J | 2 |
| K | 2 |

a. Calculate the $CR_4$ and $CR_8$.
b. Calculate the HHI for this industry.
c. Under the [current Horizontal Merger Guidelines (link)](https://ios20.classes.ryansafner.com/slides/4.1-slides#27), is this market not very concentrated, "moderately concentrated," or "highly concentrated"?
d. Calculate the "equivalent number" of a hypothetical market of equal-sized firms for this HHI.^[Hint: either convert to decimals, or multiply your answer by 10,000.]
e. Suppose firms D and E propose a merger. Calculate the new $CR_4$, $CR_8$, and HHI from the merger. Do you think is it likely that the FTC and DOJ would allow these two firms to merge?
f. Suppose *instead* of D and E, firms A and B propose a merger.^[i.e. start from the original market, ignore the proposed merger in Part E.] Calculate the new $CR_4$, $CR_8$, and HHI from the merger. Do you think is it likely that the FTC and DOJ would allow these two firms to merge?

\clearpage

5. Explain why it is difficult to identify whether a firm has market power just from observing its price. You can explain verbally, no need for a graph.

\clearpage

6. Explain, in your own words, the main implications for antitrust law from the following key statutes:

- Sherman Act (1890)
- Clayton Act (1914)
- Federal Trade Commission Act (1914)
- Hart–Scott–Rodino Antitrust Improvements Act (1976)

\clearpage

7. Explain the difference between the *per se* rule and the *rule of reason* in antitrust cases. What sorts of business practices fall into each category, and why?

\clearpage

8. Explain the difference between a *horizontal merger*, a *vertical merger*, and a *conglomerate merger*. How *might* a merger be pro-competitive, and how might a merger be anti-competitive?

\clearpage

9. Explain Bork's main idea behind the *Paradox of Antitrust*.


\clearpage

10. Explain Khan's main idea behind "Amazon's Antitrust Paradox" and the "Hipster Antitrust" movement.

\clearpage

# Natural Monopoly

11. Explain the logic of rate of return and common carrier regulation for natural monopoly. What is the government trying to achieve? How does it provide incentives for natural monopoly?

\clearpage

12. Suppose a typical firm in an industry has a cost structure as follows:

$$\begin{aligned}
C(q)&=20q+1200\\
MC(q)&=20\\
\end{aligned}$$

The market demand for the industry is:

$$q=50-0.1p$$

a. Calculate the (i) price, (ii) quantity, (iii) consumer surplus, and (iv) deadweight loss for the industry if it were perfectly competitive.
b. One firm of these firms achieves economies of scale and becomes the monopolist in this industry. If left to its own devices, what price and quantity will the monopolist set?
c. Calculate the (i) profit, (ii) consumer surplus, and (iii) deadweight loss in the industry under the monopoly.
d. The government decides to regulate the monopolist as a common carrier. What is the price and quantity the government would like to set in order to maximize allocative efficiency? Calculate the amount of profit would the monopolist would earn under this outcome.
e. The government recognizes the poor incentives it creates for the monopolist with its approach in Part D. Instead, it regulates the monopolist to set a price where it breaks even $(\pi=0)$.^[Note: this won't be the *minimum* of average cost, because $MC$ and $AC$ will never intersect in this cost structure. This is simply where $p=AC$.] Calculate the (i) price, (ii) quantity, (iii) consumer surplus, and (iv) deadweight loss under this scenario.^[Hint: To spare you use of the quadratic formula, the quantity will be *approximately* 45!]
