---
title: "3.2 The Firm as Nexus of Contracts - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Recommended Readings:

- [<i class="fas fa-file-pdf"></i> Alchian and Demsetz, 1972, "Production, Information Costs, and Economic Organization"](/readings/Alchian-Demsetz-1972.pdf)
- [<i class="fas fa-file-pdf"></i> Jensen and Meckling, 1976, "Theory of the Firm: Managerial Behavior, Agency Costs and Ownership Structure"](/readings/Jensen-Meckling-1976.pdf)
- [<i class="fas fa-file-pdf"></i> Jensen and Murphy, 1990, "CEO Incentives - It's Not How Much You Pay, But How"](/readings/Shleifer-Vishny-1997.pdf)
- [<i class="fas fa-file-pdf"></i> Murphy, 2012, "Executive Compensation: Where We Are, and How We Got There"](/readings/Murphy-2012.pdf)
- [<i class="fas fa-file-pdf"></i> Shleifer and Vishney, 1997, "A Survey of Corporate Governance"](/readings/Shleifer-Vishny-1997.pdf)

Alchian and Demsetz (1972) is the most important to read (and the shortest and most readable), followed by Jensen and Meckling (1976), which, after the first section, gets too lengthy and technical.

The free IO textbook only very briefly covers Alchian and Demsetz (1972) and nexus of contracts theory. It then launches into a very technical example. This book is less useful today than for last class and for next class:

- <i class="fas fas fa-book"></i> pp.79-81 in @Church^[Again, there is [a free PDF](https://works.bepress.com/jeffrey_church/23/) from the authors.]