---
title: "1.5 Monopoly I: Behavior"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, January 30, 2020* and *Thursday, February 6, 2020*

# Overview

We begin looking at monopoly by discussing how a monopolist (as compared to a price-taking firm) chooses both its output and its price to maximize profits. 

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/1.5-slides.html)

# Appendix

## Price Elasticity of Demand Refresher

**Price elasticity of demand** measures *how much* (in %) quantity demanded changes in response to a (1%) change in price.

$$\begin{align*}
\epsilon_{q,p} &= \frac{\% \Delta q}{\% \Delta p}\\
&= \cfrac{\left(\frac{\Delta q}{q}\right)}{\left(\frac{\Delta p}{p}\right)}\\
&= \frac{\Delta q}{\Delta p} \times \frac{p}{q}\\
&= \frac{1}{slope} \times \frac{p}{q}\\
\end{align*}$$


|                 | "Elastic" | "Unit Elastic" | "Inelastic" |
|-----------------|-----------|----------------|------------|
| **Intuitively**:    | *Large* response | Proportionate response | *Little* response |
| **Mathematically**: | $\vert \epsilon_{q_D,p}\vert > 1$ | $\vert \epsilon_{q_D,p}\vert = 1$ | $\vert \epsilon_{q_D,p} \vert < 1$ |
|                 | Numerator $>$ Denominator | Numerator $=$ Denominator | Numerator $<$ Denominator |
| **A 1% change in $p$** | More than 1% change in $q_D$ | 1% change in $q_D$ | Less than 1% change in $q_D$ | 

Price elasticity of demand changes along the demand curve:

```{r, fig.retina=3, echo=F, warning = F, message = F}
library(tidyverse)
library(ggrepel)
demand=function(x){10-x}

ggplot(data.frame(x=c(0,10)), aes(x=x))+
  stat_function(fun=demand, geom="line", size=2, color = "blue")+
  geom_label(aes(x=1,y=demand(1)), color = "blue", label="Demand", size = 6)+
    scale_x_continuous(breaks=seq(0,10,1),
                     limits=c(0,10),
                     expand=expand_scale(mult=c(0,0.1)))+
  scale_y_continuous(breaks=seq(0,10,1),
                     limits=c(0,10),
                     expand=expand_scale(mult=c(0,0.1)),
                     labels = function(x){paste("$", x, sep="")})+
  # line at 5,5 
  geom_segment(aes(x=0,xend=5, y=5, yend=5), linetype="dashed")+
  geom_segment(aes(x=5,xend=5, y=5, yend=0), linetype="dashed")+
  
  geom_label_repel(aes(x=0, y=10), color="purple", label=expression(epsilon == infinity))+
  geom_label_repel(aes(x=2.5, y=7.5), color="purple", label=expression(paste(epsilon > 1, ": Elastic")))+
  geom_label_repel(aes(x=5, y=5), color="purple", label=expression(paste(epsilon == 1, ": Unit Elastic")))+
  geom_label_repel(aes(x=7.5, y=2.5), color="purple", label=expression(paste(epsilon < 1, ": Inelastic")))+
  geom_label_repel(aes(x=10, y=0), color="purple", label=expression(epsilon == 0))+
  #coord_cartesian(clip="off")+
  labs(x = "Quantity of x",
       y = "Price of x")+
  theme_classic(base_family = "Fira Sans Condensed", base_size=20)
```

### Determinants of Price Elasticity

> What determines how responsive your buying behavior is to a price change?

- More (fewer) **substitutes** $\implies$ more (less) elastic
  - Larger categories of products (less elastic) vs. specific brand (more elastic)
  - **Necessities** (less elastic) vs. **luxuries** (more elastic)
  - Large (more elastic) vs. small (less elastic) **portion of budget**

- More (less) **time to adjust** $\implies$ more (less) elastic


## Derivation of the Lerner Index

Marginal revenue is strongly related to the **price elasticity of demand**, which is $E_{D}=\frac{\Delta q}{\Delta p} \times \frac{p}{q}$^[I sometimes simplify it as $E_{D}=\frac{1}{slope} \times \frac{p}{q}$, where "slope" is the slope of the inverse demand curve (graph), since the slope is $\frac{\Delta p}{\Delta q} = \frac{rise}{run}$.]

We derived marginal revenue (in the slides) as:
$$MR(q)=p+\frac{\Delta p}{\Delta q}q$$

Firms will always maximize profits where: 

$$\begin{align*}
MR(q)&=MC(q) && \text{Profit-max output}\\
p+\bigg(\frac{\Delta p}{\Delta q}\bigg)q&=MC(q) && \text{Definition of } MR(q)\\
p+\bigg(\frac{\Delta p}{\Delta q}\bigg) q \times \frac{p}{p}&=\frac{MR(q)}{p} && \text{Multiplying the left by } \frac{p}{p} \text{ (i.e. 1)}\\
p+\underbrace{\bigg(\frac{\Delta p}{\Delta q}\times \frac{q}{p} \bigg)}_{\frac{1}{\epsilon}} \times p &=MC(q) && \text{Rearranging the left}\\
p+\frac{1}{\epsilon} \times p &=MC(q) && \text{Recognize price elasticity } \epsilon=\frac{\Delta q}{\Delta p} \times \frac{p}{q}\\
p &=MC(q) - \frac{1}{\epsilon} p && \text{Subtract  }\frac{1}{\epsilon}p \text{ from both sides}\\
p-MC(q) &= -\frac{1}{\epsilon} p && \text{Subtract  }MC(q) \text{ from both sides}\\
\frac{p-MC(q)}{p} &= -\frac{1}{\epsilon} && \text{Divide both sides by  }p\\
		\end{align*}$$

The left side gives us the fraction of price that is markup $\left(\frac{p-MC(q)}{p}\right)$, and the right side shows this is inversely related to price elasticity of demand.