---
title: "3.1 Why Are There Firms?"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, March 31, 2020*

*Quarantine Lecture 3*

# Overview

Today we start looking at what is known in economics as "the theory of the firm." We begin with asking the question, "if markets are so great, why are there firms?" We look at Adam Smith's idea of the division of labor, and when specialization makes sense. Then we look at Coase's key contribution - that firms exist because there are transaction costs of using markets. We wrap up with Stigler's relation of the division of labor to the life cycle of industries.

For the next few classes, we will look at other aspects of the theory of the firm, and address why firms look and behave the way they do, by understanding the economic problems that organizations try to solve.

# Readings

See today's [readings](/reading/3.1-reading) which may help you understand the concepts, and which are the primary source of what I discuss today.

# Class Livestream/Lecture Videos

<iframe width="560" height="315" src="https://www.youtube.com/embed/7ABWUaqTJKg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/NUumF-XVrQg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/7pmvNmmx0RQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/Uc7gz9Ah2Gc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/VwIorrTTUBk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/3.1-slides.html)

# Assignments: Homework 2, Midterm Exam

[Homework 2](assignment/02-problem-set) is posted, and is due via email, on Sunday, April 5, by 11:59PM. The answer key will be posted Monday, April 6. **Please attach your document as a PDF!**

Homework 1 grades are on Blackboard and the answer key is on the original assignment page.

Our midterm exam will be the week of April 6. It will likely be a take home series of questions that you can spend a few days to work on, and will email to me when you complete.

# Midterm Course Grades

As per the Registrar, all faculty were required to issue midterm course grades on Monday March 30. I *estimated* your grade based on the assignments we have completed so far - just HW 1. You can again estimate your final course grade (out of 100%) on the [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/326_grade_calculator/) at the top of the [Assignments page](/assignments).
