---
title: "3.4 Contractual Restraints & Property Rights"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, April 9, 2020*

*Quarantine Lecture 6*

# Overview

Today we look at the other major solution to post-contractual opportunism caused by asset specificity: writing restrictive long-term contracts. We look at examples such as franchising, exclusivity agreements, territorial restraints, and resale price maintenance. All of these will be important once we start considering antitrust concerns.

Finally, we discuss a fourth perspective on the firm, the ["property rights approach"](https://en.wikipedia.org/wiki/Property_rights_(economics)#Property_rights_approach_to_the_theory_of_the_firm), largely affiliated with 2016 Nobel Laureate Oliver Hart. This view argues that firms are defined by their ownership of assets, and the key aspect of ownership is *residual control rights*: that owners can make decisions for all cases not clearly specified in contracts. The key takeaway is that who owns assets matters for efficiency.

# Readings

See today's [readings](/reading/3.4-reading) which may help you understand the concepts, and which are the primary source of what I discuss today.

# Class Livestream/Lecture Videos

<iframe width="560" height="315" src="https://www.youtube.com/embed/lcZozyvebn4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/Z6TVnlA_Vx4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/5WI9jwdEEk8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/iOsNy3l8DIM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/3.4-slides.html)

# Discussion Board

I have opened up a discussion board on Blackboard^[Go to this course on Blackboard, on the blue navigation bar on the left, see Discussion Board.] on the theory of the firm for this week and next week's topics. You can use this to post questions, comments, or anything you'd like us to talk about regarding the theory of the firm. There are a lot of interpretations, and a fair amount of different literatures on this, so I am happy to discuss this. I am also genuinely curious and interested in what you think.

For now, I am not grading this in any way. Use this as a way to connect and make sure we are understanding the readings. (And I really enjoyed our first discussion!)

Perhaps later, when we get to applications and policy, we will take this up more seriously and I will grade for participation.

# Assignments: Midterm Exam Due 8 PM Saturday April 11

Our midterm is [posted](/assignment/midterm), and is due **by email as a PDF at 8:00PM Saturday April 11**.
