---
title: "Final Exam"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

- *Due 8:00 PM Friday, May 8 by email (PDF)*

# Instructions

**Choose five (5)** questions to answer. Questions draw from course lectures, discussions, and readings. Each question is worth **20 points.**

You may discuss the questions, but you must write your own responses and turn in your own work. Answers that are substantially similar will be interpretted cheating and punished accordingly. I will not answer any questions about course content during while the exam is outstanding.

This assignment is due by **8:00 PM May, April 8 by email**. Starting at 8:01, you will lose 2 points for every hour it is late.

*If appropriate*, you must be able to talk with some familiarity about arguments put forth in our readings, when relevant (informally, as in "According to Smith..."). You do not need formal citations, but it should be clear when you are referencing the readings vs. your own thinking. *This is not relevant for all questions!*

1. Alchian and Demsetz (1972) famously argue that:

> "It is common to see the firm characterized by the power to settle issues by fiat, by authority, or by disciplinary action superior to that available in the conventional market. This is delusion."

> Basing your argument on any approach(es) to the theory of the firm, do you agree or disagree with Alchian and Demsetz? Explain why. 

2. Explain several possible goals or perspectives to antitrust law that we have discussed.

3. Explain an argument to bring an antitrust case against Amazon (and on what grounds), and on what grounds a case should *not* be brought against Amazon. Which do you find more compelling, and why?

4. Suppose you observe all firms in an industry charging the same price. What kind(s) of market structure might this industry be? How could you potentially identify it (what data would you need)? Think carefully!

5. Explain the problems of "horizontal free riding" and "vertical free riding." How do firms write contracts (for example, in franchise contracts) to overcome these problems?

6. Compare and contrast the rights and abilities of the "firm" according to the nexus of contracts view and the property rights view.

7. Explain how the "market for corporate control" can reduce agency costs regarding a firm's management.

8. Explain several conceptual reasons why vertical integration may not be anti-competitive. What economic problems may vertical integration be solving, and how? 

9. Given what we have discussed in class this semester, what types of business practices do you think should fall under the *per se* rule, and which should fall under the *rule of reason* in antitrust litigation?

10. Which topic or concept this semester was your favorite, or you found most surprising or interesting, and why?