---
title: "Midterm"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

- *Due 8:00 PM Saturday, April 11 by email (PDF)*

# Instructions

Choose four questions to answer. Questions draw from course lectures, discussions, and readings.

You may discuss the questions, but you must write your own responses and turn in your own work. Answers that are substantially similar will be interpretted cheating and punished accordingly. I will not answer any questions about course content during while the exam is outstanding.

Each question is worth **25 points.** This assignment is due to me by email by **8:00 PM Saturday, April 11 by email as a PDF**. Starting at 8:01, you will lose 2 points for every hour it is late.

1. Explain why, in Stackelberg competition, the Leader cannot^[Or to be clearer, it would not be *rational* for the Leader to] act like a pure monopolist would.

2. Verizon currently provides the *only* cellular service in a remote area. Assume Verizon has a constant marginal cost per internet connection, and has no fixed costs.

a. (10 points) Under what conditions is this market with a single producer *both* a competitive outcome and a Nash equilibrium?

b. (5 points) What if Verizon has fixed costs? How will this Nash equilibrium change? Compare this to the monopoly and the competitive outcomes.

c. (10 points) Suppose T-Mobile is considering providing service in this remote area as well. However, TA-Mobile has significantly higher costs than Verizon. What will the Nash equilibrium of this market be? Compare this to the monopoly and the competitive outcomes.

3. Explain what game theorists mean by the phrase "talk is cheap." Use the concept of *subgame perfect Nash equilibrium* in your answer.

4. How does "uncertainty" explain the origin of economic profits in the real world, as opposed to the long run equilibrium prediction of the perfect competition model? Make use of the readings in your answer.^[You must be able to talk with some familiarity about arguments put forth in our readings, when relevant (informally, as in "According to Smith..."). You do not need formal citations, but it should be clear when you are referencing the readings vs. your own thinking.]

5. Briefly describe four^[Where a cartel is one of them.] different models of oligopoly, and rank them according to which model yields the highest industry price, highest quantity of industry output, and highest profits.

6. People often ridicule the perfect competition model as unrealistic given its heroic assumptions about firms and markets. React to this argument, given what we have read and discussed this semester.